config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  devise_for :users

  # static pages
  post "pages/send_contact_us"
  get "heres-how",            :controller => :pages, :action => :heres_how
  get "contact-us",           :controller => :pages, :action => :contact_us
  get "about-us",             :controller => :pages, :action => :about_us
  get "faq",                  :controller => :pages, :action => :faq
  get "privacy-policy",       :controller => :pages, :action => :privacy
  get "terms-of-service",     :controller => :pages, :action => :terms
  get "shipping",             :controller => :pages, :action => :shipping
  get "returns-exchanges",    :controller => :pages, :action => :returns_exchanges
  get "sizing",               :controller => :pages, :action => :sizing
  get "process",              :controller => :pages, :action => :processing
  get "pinterest-56764.html", :controller => :pages, :action => :pinterest
  get "win",                  :controller => :pages, :action => :win
  get "user-agreement",       :controller => :pages, :action => :user_agreement

  resources :orders, :only => [:index, :show]

  # checkout pages
  resources :cart, :only => [:index, :show] do
    collection do
      get  :checkout
      get  :creditcard
      post :checkout
    end
  end

  namespace :api do
    get 'carts/shipping_cost', :controller => :carts, :action => :shipping_cost
    resources :carts, :only => [:index, :show, :create, :destroy]
    resources :coupons, :only => :show
    resources :unfinished_orders, :only => :create
    resources :products, :only => [:index, :show] do
      resources :product_types, :only => [:index, :show]
      resources :product_type_colors, :only => [:index]
    end
    # resources :product_types, :only => [:index, :show]
  end

  namespace :checkout do
    resources :paypal, :only => [:show]
    resources :eway,   :only => [:create]
  end

  # get "dashboard", :controller => 'dashboard/home', :action => :index
  get "my-orders", :controller => 'dashboard/home', :action => :index
  namespace :dashboard do
    resources :orders, :only => [:index, :show, :update] do
      resources :order_items, :only => [:index, :show]
    end
  end

  get "render_email_pixel/:time_frame", :controller => :mail_tracker, :action => :render_pixel, :as => :render_email_pixel

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'f@nt33s'
  end
  mount Sidekiq::Web => '/sidekiq'

  get ":slug", :controller => "products", :action => :show
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  belongs_to :product_type
  belongs_to :size

  def self.create_cart_items(items, user, cart_tracking_code)
    user_id = user.nil? ? nil : user.id
    items.each do |i|
      item = {
        :user_id         => user_id,
        :product_id      => i[:product_id],
        :size_id         => i[:size_id],
        :product_type_id => i[:product_type_id],
        :price           => i[:price],
        :quantity        => i[:quantity],
        :tracking_code   => cart_tracking_code
      }

      begin
        carts = Cart.where tracking_code: cart_tracking_code, product_id: i[:product_id], product_type: i[:product_type_id], size_id: i[:size_id]
        if carts.count > 0
          carts.first.increment!(:quantity, i[:quantity])
        else
          Cart.create item
        end
      rescue
      end
    end

    Cart.where tracking_code: cart_tracking_code
  end

  def self.create_tracking_code
    code ||= loop do
      random_code = SecureRandom.hex[0..12].upcase
      break random_code unless Cart.exists?(tracking_code: random_code)
    end

    return code
  end

end

app/controllers/api/carts_controller.rb
class Api::CartsController < ApplicationController
  def index

  end

  def show
    @item = Cart.find params[:id]
  end

  def create
    # checks if previous items are from admin if not will delete all and insert new items
    if session[:cart]["is_admin"] == false
      session[:cart]['is_admin'] = true
      cart = Cart.where tracking_code: session[:cart]['tracking_code']
      cart.delete_all
    end

    cart = Cart.create_cart_items params[:items], current_user, session[:cart]['tracking_code']

    render :json => {items: cart}
  end

  def destroy
    cart = Cart.find(params[:id])
    cart.delete

    @cart = Cart.where tracking_code: session[:cart]['tracking_code']
    items = []
    @cart.all.each do |item|
      items << {
        id:              item.id,
        quantity:        item.quantity,
        size:            item.size_id,
        price:           item.price,
        image:           item.product_type.front_image(:thumb),
        product_title:   item.product.title,
        size_name:       item.size.name,
        product_type_id: item.product_type_id,
        delivery_date:   item.product.end_campaign + 14.days,
        type_name:       item.product_type.name_and_color
      }
    end

    render :json => {items: items}
  end

  def shipping_cost
    render :json => {cost: Shipping.compute_shipping_cost('cart', session[:cart]['tracking_code'])}
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  layout 'products'

  def index
    @order = Order.new
    gon.coupon  = Coupon.find_by code: session[:cart]['coupon']
  end

  def show
    session[:cart]['tracking_code'] = params[:id]

    @cart  = Cart.where tracking_code: params[:id]
    @uo    = UnfinishedOrder.find_by tracking_code: params[:id]
    @order = Order.new

    if @cart.empty?
      session[:cart]['tracking_code'] = Cart.create_tracking_code
      redirect_to '/500.html'
    else
      if @uo
        session[:rebuild] = true

        # add mail tracker for email clicks
        if params[:time_frame]
          time_frame = ""
          case params[:time_frame]
          when "30m"
            time_frame = "30-minutes"
          when "1d"
            time_frame = "1-day"
          when "10d"
            time_frame = "10-days"
          end

          MailTracker.increment_count("click", time_frame)
          session[:rebuild_time_frame] = time_frame
        end

        gon.coupon = Coupon.find_by code: session[:cart]['coupon']
        begin
          gon.order  = eval(@uo.checkout_info)
        rescue
          gon.order  = order_fields
        end

        # render :json => gon.order
        render 'creditcard'
      end
    end
  end

  def creditcard
    @order = Order.new
    if params[:order]
      gon.order  = params[:order]
      gon.coupon = Coupon.find_by code: session[:cart]['coupon']
    else
      gon.coupon = Coupon.find_by code: session[:cart]['coupon']
      gon.order  = order_fields
    end
  end

  def checkout
    # add_to_cart if params[:items]
    if params[:items] && params[:payment] == 'creditcard'
      add_to_cart
      creditcard_checkout
    else
      paypal_checkout
    end
  end

  private

  def paypal_checkout
    add_to_cart if params[:items]
    shipping = Shipping.compute_shipping_cost('cart', session[:cart]['tracking_code'])
    paypal   = Purchase.new 'paypal', @cart, {shipping: shipping, coupon: session[:cart]['coupon']}
    @cart    = Cart.where tracking_code: session[:cart]['tracking_code']

    begin
      pid      = @cart.last.product_id
    rescue
      redirect_to root_path
    end

    product  = Product.find pid

    express_checkout_url = paypal.redirect_url(
      :ip                => request.remote_ip,
      :return_url        => checkout_paypal_url(session[:cart]['tracking_code']),
      :cancel_return_url => "#{root_url}#{product.slug}"
    )

    if paypal.errors[:status] != 'Error'
      redirect_to express_checkout_url
    else
      render :json => paypal.errors
    end
  end

  def creditcard_checkout
    redirect_to creditcard_cart_index_path
  end

  def add_to_cart
    session[:cart][:is_admin] = false

    cart = Cart.where tracking_code: session[:cart]['tracking_code']
    cart.delete_all

    @cart = Cart.create_cart_items params[:items], current_user, session[:cart]['tracking_code']
  end

  def order_fields
    {
      :email      => "",
      :first_name => "",
      :last_name  => "",
      :phone      => "",
      :address    => "",
      :city       => "",
      :phone      => "",
      :zip        => "",
      :country_code => @website.name == "FanTees-NZ" ? "NZ" : "AU",
      :country_name => @website.name == "FanTees-NZ" ? "New Zealand" : "Australia",
      :state      => "",
      :cc_number  => "",
      :month      => 1.month.from_now.strftime("%m").to_i,
      :year       => 1.month.from_now.strftime("%Y").to_i,
      :cvn        => ""
    }
  end

end

app/views/cart/creditcard.html.haml
.main-content.customer-info-page.ng-scope{"ng-controller" => "CartCreditCardCtrl"}
  / landing-page-content
  = form_for @order, url: checkout_eway_index_path, html: {'ng-submit' => "submitForm()"} do |f|
    .center
      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-left
        %h2 Customer Information
        #info.form
          .radio
            %label{:for => "ci-email"} Email
            %input#ci-email.ng-pristine.ng-valid{:name => "order[email]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.email", :placeholder => "john.doe@email.com", :type => "text"}
            .clearfix
          %h3 Shipping Address
          .radio.fname-border
            %label{:for => "ci-fname"} First Name
            %input#ci-fname.ng-pristine.ng-valid{:name => "order[first_name]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.first_name", :placeholder => "John", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-lname"} Last Name
            %input#ci-lname.ng-pristine.ng-valid{:name => "order[last_name]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.last_name", :placeholder => "Doe", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-address"} Address
            %input#ci-address.ng-pristine.ng-valid{:autocomplete => "off", :name => "order[address]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.address", :placeholder => "123 ABC Street", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-state"} Suburb/Town
            %input#ci-town.ng-pristine.ng-valid{:name => "order[city]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.city", :placeholder => "City", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-state"} State
            %input#ci-state.ng-pristine.ng-valid{:name => "order[state]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.state", :placeholder => "State", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-pcode"} Postal Code
            %input#ci-pcode.ng-pristine.ng-valid{:autocomplete => "off", :name => "order[zip]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.zip", :placeholder => "1110", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-country"} Country
            %input#ci-ccode{:name => "order[country_code]", "ng-value" => "checkout.country_code", :type => "hidden"}
            %input#ci-country.ng-pristine.ng-valid{"ng-blur" => "fieldBlur()", :name => "order[country_name]", "ng-change" => "selectCountry(this)", "ng-model" => "checkout.country_name", :placeholder => "Australia", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1.phone-border
            %label{:for => "ci-phone"} Phone
            %input#ci-phone.ng-pristine.ng-valid{:name => "order[phone]", "ng-blur" => "fieldBlur()", "ng-model" => "checkout.phone", :placeholder => "66 7 3188 5168", :type => "text"}
            .clearfix
          %h3 Billing & Payment
          .radio.fname-border
            %label{:for => "ci-cards"} Credit Card
            %p.cards-holder
              %img{:src => "/assets/cards.png"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-card-number"} Credit Number
            %input#ci-card-number.ng-pristine.ng-valid{:name => "order[cc_number]", "ng-model" => "checkout.cc_number", :placeholder => "----  ----  ----  ----", :type => "text"}
            .clearfix
          .radio.border-rad0.margtop-1
            %label{:for => "ci-expiry"} Expiry
            .col-lg-12.nopadding.select2
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                = select_month nil, {add_month_numbers: true}, {name: 'order[month]', "ng-model" => "checkout.month"}
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: 'order[year]', "ng-model" => "checkout.year"}
              .clearfix
            .clearfix
          .radio.border-rad0.margtop-1.phone-border
            %label{:for => "ci-ccv"} CCV
            %input#ci-ccv.ng-pristine.ng-valid{:name => "order[cvn]", "ng-model" => "checkout.cvn", :placeholder => "123", :type => "text"}
            .clearfix
          %input.place-order-now{:type => "submit", :value => "Place My Order Now"}
          %img{:src => "/assets/sponsor-logo.png", :style => "display:block; margin: 0 auto;"}
          .clearfix
      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-right
        .order-summary{'ng-cloak' => ""}
          .order-summary-header
            %h3 Order Summary
          .order-summary-body
            / ngRepeat: item in items
            .item-summary{:'ng-repeat' => "item in items"}
              %a#item1-close.close-black{:href => "#", 'ng-click' => "removeItem(item.id)"}
              %ul
                %li
                  %img{:alt => "shirt", :'ng-src' => "{{item.image}}"}
                  .product-info{:style => "margin-top: 5px"}
                    %span.product-info-name
                      %strong {{item.product_title}}
                    %span.product-info-description
                      {{item.quantity}} pc(s) {{item.size_name}} - {{item.type_name}}

                  %span.shirt-value {{item.price * item.quantity  | currency:"$"}}
                  .clearfix
              %span.arrive-due-date Your order is due to arrive on {{item.delivery_date | niceDate}}

            - if Rails.env.development?
              .discount
                %a.discount-link.ng-hide{:href => "#", "ng-click" => "toggleCoupon()", "ng-show" => "!show_coupon"} Have a discount code? Click here to enter it
                #coupon-discount-form.discount-form{"ng-show" => "show_coupon"}
                  %label{:for => "checkout_discount_code"} Discount
                  %input#checkout_discount_code.ng-pristine.ng-valid{:name => "order[coupon_code]", "ng-model" => "coupon.code", :placeholder => "......", :size => "30", :type => "text"}
                  %input.discount-btn{:name => "commit", "ng-click" => "applyCoupon()", :type => "button", :value => "Apply"}
            .order-summary-section
              %ul
                %li
                  Subtotal
                  %span.ng-binding {{total  | currency:"$"}}
                %li
                  Shipping
                  %span.ng-binding {{shipping  | currency:"$"}}
                %li{'ng-show' => "coupon.discount"}
                  Discount
                  %span.ng-binding {{coupon.discount}}%
                %li
                  Total
                  %span.ng-binding {{total + shipping  | currency:"$"}}
            .payment-due
              %p
                Payment Due
                %span.due-value.ng-binding
                  %span.currency aud
                  {{total + shipping - discount  | currency:"$"}}
      .clearfix
  %script{:src => "//expresscapture.datatoolscloud.net.au/js/expresscapture-2.20.min.js?key=UE93-DR37-AT75-PU78", :type => "text/javascript"}
  %link{:href => "//expresscapture.datatoolscloud.net.au/css/expresscapture-2.20.min.css?key=UE93-DR37-AT75-PU78", :rel => "stylesheet", :type => "text/css"}

app/views/cart/index.html.haml
.main-content.customer-info-page{:'ng-controller' => "CartListCtrl"}
  / landing-page-content
  .center
    = form_for :order, url: checkout_cart_index_path(:payment => "PP") do |c|
      - unless @errors.blank?
        .alert.alert-danger
          %ul{:style => "margin: 0;"}
            - @errors.each do |err|
              %li=err

      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-right
        .order-summary
          .order-summary-body

            .item-summary{:'ng-repeat' => "item in items"}
              %a#item1-close.close-black{:href => "#", 'ng-click' => "removeItem(item.id)"}
              %ul
                %li
                  %img{:alt => "shirt", :'ng-src' => "{{item.image}}"}
                  .product-info{:style => "margin-top: 5px"}
                    %span.product-info-name
                      %strong {{item.product_title}}
                    %span.product-info-description
                      {{item.quantity}} pc(s) {{item.size_name}} - {{item.type_name}}

                  %span.shirt-value {{item.price * item.quantity  | currency:"$"}}
                  .clearfix
              %span.arrive-due-date Your order is due to arrive on {{item.delivery_date | niceDate}}

      .col-lg-6.col-md-6.col-sm-6.col-xs-12.customer-info-right
        .order-summary
          .order-summary-header
            %h3 Order Summary
          - if Rails.env.development?
            .discount
              %a.discount-link{:href => "#", "ng-click" => "toggleCoupon()", "ng-show" => "!show_coupon"} Have a discount code? Click here to enter it
              #coupon-discount-form.discount-form{"ng-show" => "show_coupon"}
                %label{:for => "checkout_discount_code"} Discount
                %input#checkout_discount_code.ng-pristine.ng-valid{"ng-model" => "coupon.code", :placeholder => "......", :size => "30", :type => "text"}
                %input.discount-btn{:name => "commit", "ng-click" => "applyCoupon()", :type => "button", :value => "Apply"}
          .order-summary-section
            %ul
              %li
                Subtotal
                %span.ng-binding {{total  | currency:"$"}}
              %li
                Shipping
                %span.ng-binding {{shipping  | currency:"$"}}
              %li{'ng-show' => "coupon.discount"}
                Discount
                %span.ng-binding {{coupon.discount}}%
              %li
                Total
                %span.ng-binding {{total + shipping | currency:"$"}}
          .payment-due
            %p
              Payment Due
              %span.due-value.ng-binding
                %span.currency aud
                {{total + shipping - discount | currency:"$"}}
        .checkout-btn
          %a.green{:href => creditcard_cart_index_path} Checkout via Card
          %a.btn-sm-custom-pop02.popup-checkout-button{:href => checkout_cart_index_path}
            Checkout with
            %span Paypal

      .clearfix