config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  devise_for :users

  # static pages
  post "pages/send_contact_us"
  get "heres-how",            :controller => :pages, :action => :heres_how
  get "contact-us",           :controller => :pages, :action => :contact_us
  get "about-us",             :controller => :pages, :action => :about_us
  get "faq",                  :controller => :pages, :action => :faq
  get "privacy-policy",       :controller => :pages, :action => :privacy
  get "terms-of-service",     :controller => :pages, :action => :terms
  get "shipping",             :controller => :pages, :action => :shipping
  get "returns-exchanges",    :controller => :pages, :action => :returns_exchanges
  get "sizing",               :controller => :pages, :action => :sizing
  get "process",              :controller => :pages, :action => :processing
  get "pinterest-56764.html", :controller => :pages, :action => :pinterest
  get "win",                  :controller => :pages, :action => :win
  get "user-agreement",       :controller => :pages, :action => :user_agreement

  resources :orders, :only => [:index, :show]

  # checkout pages
  resources :cart, :only => [:index, :show] do
    collection do
      get  :checkout
      get  :creditcard
      post :checkout
    end
  end

  namespace :api do
    get 'carts/shipping_cost', :controller => :carts, :action => :shipping_cost
    resources :carts, :only => [:index, :show, :create, :destroy]
    resources :coupons, :only => :show
    resources :unfinished_orders, :only => :create
    resources :products, :only => [:index, :show] do
      resources :product_types, :only => [:index, :show]
      resources :product_type_colors, :only => [:index]
    end
    # resources :product_types, :only => [:index, :show]
  end

  namespace :checkout do
    resources :paypal, :only => [:show]
    resources :eway,   :only => [:create]
  end

  # get "dashboard", :controller => 'dashboard/home', :action => :index
  get "my-orders", :controller => 'dashboard/home', :action => :index
  namespace :dashboard do
    resources :orders, :only => [:index, :show, :update] do
      resources :order_items, :only => [:index, :show]
    end
  end

  get "render_email_pixel/:time_frame", :controller => :mail_tracker, :action => :render_pixel, :as => :render_email_pixel

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'f@nt33s'
  end
  mount Sidekiq::Web => '/sidekiq'

  get ":slug", :controller => "products", :action => :show
end

app/views/pages/about_us.html.haml
%div{:'ng-controller' => "PagesCtrl"}
  .main-content.aboutus-content
    .center
      %h2 About Us
      %p We love the work we do and the jobs we have, we love them so much we made T-Shirts pro-claiming what we do. After doing it for ourselves we thought “wait, we aren’t the only ones who love what we do, so why not make t-shirts for other people who love what they do”.
      %p With that, FanTees.com.au was born and we now spend our spare time designing and selling t-shirts related to all the weird, wacky and fun jobs people do in the hopes you’ll love them just as much as we do!

app/views/pages/contact_us.html.haml
%div{:'ng-controller' => "PagesCtrl"}
  .main-content.contactus-page
    .center
      %h2.text-center Contact Us
      %h3 Have a Questions our FAQ don’t answer? Send us a Message and We’ll get back to you ASAP!
      - flash.each do |name, msg|
        - if name == :error
          .alert.alert-danger.alert-dismissable
            %button.close{ :type => "button", :aria => { :hidden => "true" }, :data => { :dismiss => "alert" } } &times;
            %ul{ :style => "list-style:none;" }
              - msg.each do |m|
                %li
                  %h2{ :style => "margin-bottom:0px;" }
                    = m
        - else
          .alert.alert-success.alert-dismissable
            %button.close{ :type => "button", :aria => { :hidden => "true" }, :data => { :dismiss => "alert" } } &times;
            %h2{ :style => "margin-bottom:0px;" }
              = msg

      .col-lg-6.col-md-6.col-sm-6.col-xs-12.contactus-left
        = form_for :contact, :url => pages_send_contact_us_path, :remote => false, :html => {:class => "contactus-form"} do |f|
          = f.text_field :name, {class: "name", placeholder: "Name"}
          = f.text_field :email, {placeholder: "Email Address"}
          = f.text_field :subject, {placeholder: "Subject"}
          = f.text_area :message, {placeholder: "Message", rows: "5"}
          = f.submit "Submit"

      .col-lg-6.col-md-6.col-sm-6.col-xs-12.contactus-right
        .blue-box
          .col-lg-6.col-md-6.col-sm-6.col-xs-12
            %p TRACK YOUR ORDER
            %a.box-btn.blue-btn{:href => "/dashboard/#/orders"} Search
          .col-lg-6.col-md-6.col-sm-6.col-xs-12
            %p CHECK OUR FAQ
            %a.box-btn.green-btn{:href => "/faq"} Go to FAQ Page
          .clearfix
        .clearfix
        %h4 CALL OUR SUPPORT TEAM
        %ul
          %li
            %i.fa.fa-phone
            1300 76 65 67
          %li
            %i.fa.fa-support
            Support hours : Monday - Friday 9AM - 6PM (AEST)
        %h4 WANT TO SNAIL MAIL SOMETHING TO US?
        %ul
          %li
            %i.fa.fa-map-marker
            Brendale Business Hub
            %br/
            %i.fa.fa-map-marker
            PO Box 5583
            %br/
            %i.fa.fa-map-marker
            Brendale DC, QLD 4500
      .clearfix

app/views/pages/faq.html.haml
%div{:'ng-controller' => "PagesCtrl"}
  .main-content.faqs-content
    .center
      %h2 FAQ
      %p What Is A Campaign?
      %p We're a bit different to other apparel stores, we only print our designs (campaigns) if we reach a minimum number of orders, once we reach that minimum we start printing and shipping your order!
      %p Can You Do Custom Designs &amp; Orders?
      %p We certainly can! For a custom design to work we need a minimum of 25 orders before we send the design to print.
      %p What about bulk orders?
      %p Yup, no problems, just reach out to us and we’ll be able to help you out with your order.
      %p How long does it take for my order to be delivered?
      %p Your order will arrive 10-14 business days from the end of the campaign. If your order hasn’t arrived inside the estimated delivery times, please contact our support team.
      %p How much does shipping cost?
      %p Domestic shipping prices are calculated on checkout, if you order 2 or more items at once shipping is free. If you are outside Australia and wish to purchase a shirt please contact our support team so we can discuss shipping options with you.
      %p Who designs the t-shirts?
      %p The designs are 100% original and are designed by us here at FanTees.com.au
      %p Where are the t-shirts printed?
      %p We screen print the designs on the t-shirts here locally in Brisbane, Australia ensuring you’ll be receiving the highest quality t-shirts possible.
      %p Is buying online safe?
      %p Ofcourse! Nothing to worry about, our site is protected by a 128-bit SSL (what this means is that all your details are 100% secure!).
      %p How can I contact you?
      %p
        Jump over to our
        %a{:href => "#"} Contact page here
        and you’ll be able to either email or call us

app/views/pages/heres_how.html.haml
#learn.homepage-content-wrap
  / homepage-content-wrap
  .container
    .row
      .col-lg-7.col-md-7.col-sm-7.col-xs-12
        %h2 It’s free and easy to sell merch with FanTees
        %p FanTees will work with you to create an amazing, high quality product that fits the needs of your fans or audience.
        .row
          .col-lg-3.col-md-3.col-sm-3.col-xs-12.text-center.testi1-photo
            = image_tag "jo.png", alt: ""
          .col-lg-9.col-md-9.col-sm-9.col-xs-12
            .say-box
              %p “I absolutely LOVE my “Scumbag College” tank top! FanTees you Rock!”
              %span.say-name
                Jo Boyd
                %br/
                Facebook
      .col-lg-5.col-md-5.col-sm-5.col-xs-12.text-center.circle-img
        = image_tag "gif-1-animation.gif", {alt: "", class: "first-gif"}

.stats-wrap
  / stats-wrap
  .container
    %h2 How much could I be Earning
    %p Use our revenue calculator to find out. Earn up to $20 per tee or $35 per hoodie sold.
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .stat-box.stat-left
          %h3 Audience Size
          .stat-content
            .row
              .col-lg-5.col-md-5.col-sm-5.col-xs-12.fans-social Facebook Fans
              .col-lg-7.col-md-7.col-sm-7.col-xs-12.fans-count
                %input#fb-fans{:name => "fb-fans", :placeholder => "0", :type => "text"}/
            .row
              .col-lg-5.col-md-5.col-sm-5.col-xs-12.fans-social Twitter Followers
              .col-lg-7.col-md-7.col-sm-7.col-xs-12.fans-count
                %input#tw-fans{:name => "tw-fans", :placeholder => "0", :type => "text"}/
            .row
              .col-lg-5.col-md-5.col-sm-5.col-xs-12.fans-social Youtube Subscribers
              .col-lg-7.col-md-7.col-sm-7.col-xs-12.fans-count
                %input#yt-fans{:name => "yt-fans", :placeholder => "0", :type => "text"}/
            .row
              .col-lg-5.col-md-5.col-sm-5.col-xs-12.fans-social Instagram Followers
              .col-lg-7.col-md-7.col-sm-7.col-xs-12.fans-count
                %input#ot-fans{:name => "ot-fans", :placeholder => "0", :type => "text"}/
                %button.btn.btn-lg.calculate Calculate
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .stat-box.stat-right
          .col-lg-6.col-md-6.col-sm-6.col-xs-12.nopadding
            %h3 Click Through Rate
            .spacer
            .stat-content
              %ul
                %li 5%
                %li 10%
                %li 20%
            .spacer
          .col-lg-6.col-md-6.col-sm-6.col-xs-12.nopadding
            %h3 Estimated Sales Revenue
            .spacer
            .stat-content
              %ul
                %li
                  $
                  %span.five-percent 0
                %li
                  $
                  %span.ten-percent 0
                %li
                  $
                  %span.twenty-percent 0
            .spacer
          .clearfix

.homepage-content-wrap.homepage-content-bg
  / homepage-content-wrap
  .container
    .row
      .col-lg-7.col-md-7.col-sm-7.col-xs-12
        %h2 Why should I launch a campaign with FanTees?
        %p Avoid the typical complications, stresses and expenses involved with running your ecommerce store.
        %p
          There are no set-up fees, no design fees and no costs
          associated with buying and housing stock.
        %p We manage everything from start to finish using our established network of quality suppliers and our 30+ team of creative professionals.
        .row
          .col-lg-3.col-md-3.col-sm-3.col-xs-12.text-center.testi2-photo
            = image_tag "olivia.png", alt: ""
          .col-lg-9.col-md-9.col-sm-9.col-xs-12
            .say-box
              %p “The tee was a hit for my Mums Christmas present. Thanks Fantees - such great and fast service!!! Merry Christmas ”
              %span.say-name
                Olivia Rickerby
                %br/
                Facebook
      .col-lg-5.col-md-5.col-sm-5.col-xs-12.text-center.circle-img.nofeehassle
        = image_tag "gif-2-animation.gif", {alt: "", class: "second-gif"}

.homepage-content-wrap
  / homepage-content-wrap
  .container
    .row
      .col-lg-5.col-md-5.col-sm-5.col-xs-12.text-center.circle-img.nofeehassle
        = image_tag "gif-animation-3.gif", {alt: "", class: "third-gif"}
      .col-lg-7.col-md-7.col-sm-7.col-xs-12
        %h2 Second to none customer service!
        %p Let’s be honest, your time is too valuable to be caught up dealing with orders, fulfilment and customer service.
        %p So once we have nailed a design - we take care of all the heavy lifting. We will manufacture & ship the product directly to your fans.
        %p We’ll also be your customer first point of call for any service issues. Our customer service is something we’re really, really good at.
        .row
          %p
          .col-lg-3.col-md-3.col-sm-3.col-xs-12.text-center.testi3-photo
            = image_tag "jamie.png", alt: ""
          .col-lg-9.col-md-9.col-sm-9.col-xs-12
            .say-box
              %p Working with Fantees has been a fantastic experience and very profitable fundraiser for our BMX club. From the first contact I had with Rick the whole process was incredibly easy. Fantees designed our shirts and hoodies, sent the proof through we chose the pricing and it was uploaded on their website for sale with links for us to promote within days. They even handled the postage for us. At the end of the sale campaign the proceeds were deposited into our account almost immediately. To be honest we couldn't believe how well it all came together. Thank you Fantees for your help and support.
              %span.say-name
                Anne Williams
                %br/
                Byford BMX Club
                %br/
                Byford WA

app/views/pages/pinterest.html.haml
%table{:background => "http://passets-ak.pinterest.com/images/paper.jpg", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td#wrapper{:style => "padding:20px 20px 40px;"}
      %table#content{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "620"}
        / begin Branding Header
        %tr
          %td#logo{:align => "center", :style => "padding:20px 0 40px;"}
            %a{:href => "http://www.pinterest.com/website/verify/", :style => "border:none;", :title => "Verify domain"}
              %img{:alt => "Verify website", :height => "52", :src => "http://passets-ak.pinterest.com/images/email/logo.gif", :style => "vertical-align:top;outline:none;border:none;", :width => "200"}/
        / end Branding Header
        / begin Primary Section Header
        %tr
          %td.header{:align => "center", :background => "http://passets-ec.pinterest.com/images/mail/double_rules620.gif"}
            %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0"}
              %tr
                %td{:background => "http://passets-ak.pinterest.com/images/paper.jpg", :style => "background-color:#f7f5f5;"}
                  %h1{:style => "font-family:georgia,serif;font-weight:normal;font-size:22px;line-height:21px;color:#211922 !important;text-shadow:0 1px 0 #FFFFFF;margin:0;padding:0 20px;"}
                    Hi, FanTees!
        / end Primary Section Header
        / begin Comment
        %tr
          %td.comment_wrap{:style => "padding:30px 0 30px 8px;"}
            %table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
              %tr
                %td{:style => "background-color:#eceaeb", :width => "1"}
                %td{:style => "background-color:#FFFFFF;padding:0px;border-top:1px solid #eae9e9;border-bottom:1px solid #b2b1b1;border-left:1px solid #d4d2d3;border-right:1px solid #d4d2d3;"}
                  %table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
                    %tr
                      %td
                        %table.comment_container{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "617"}
                          %tr
                            %td.profile_image{:valign => "top", :width => "80"}
                              %a{:href => "http://www.pinterest.com/website/verify/", :title => "FanTees"}
                                %img{:alt => "FanTees", :height => "80", :src => "http://media-cache-ec0.pinimg.com/avatars/fantees_1408330089_140.jpg", :style => "vertical-align:top;outline:none;border:none;", :width => "80"}/
                            %td.comment_text{:width => "341"}
                              %p{:style => "font-family:'helvetica neue',helvetica,arial,sans-serif;font-size:14px;color:#211922;line-height:20px;text-shadow:0 1px 0 #FFFFFF;margin:0;padding:5px 0 5px 15px;"} Looking good! You are ready to return to the verification page and complete the process.
                            %td.button_row{:align => "right", :style => "padding:20px;", :width => "140"}
                              %table.button{:border => "0", :cellpadding => "0", :cellspacing => "0"}
                                %tr
                                  %td.button_text{:align => "center", :background => "http://passets-ak.pinterest.com/images/mail/button_borderless.gif", :height => "34", :style => "background-repeat:repeat-x;-moz-border-radius:6px;-webkit-border-radius:6px;-o-border-radius:6px;-ms-border-radius:6px;-khtml-border-radius:6px;border-radius:6px;background-position:top left;background-color:#d43638;border:1px solid #910101;white-space:nowrap;height:34px;"}
                                    %a{:href => "http://www.pinterest.com/website/verify/", :style => "color:#fcf9f9;cursor:pointer;text-align:center;text-decoration:none;vertical-align:baseline;", :title => "Go To Board"}
                                      /[if gte mso 9]   
                                      %span{:style => "padding:9px 15px;color:#fcf9f9;text-decoration:none;color:#fcf9f9;font-family:'helvetica neue',helvetica,arial,sans-serif;font-weight:bold;font-size:18px;line-height:18px;text-shadow:0 -1px #933640;white-space:nowrap;"} Go To Pinterest
                                      /[if gte mso 9]   
                %td{:style => "background-color:#eceaeb", :width => "1"}
              %tr
                %td{:style => "background-color:#eceaeb", :width => "1"}
                %td{:height => "1", :style => "background-color:#d5d3d4"}
                %td{:style => "background-color:#eceaeb", :width => "1"}
              %tr
                %td{:width => "1"}
                %td{:height => "1", :style => "background-color:#e8e6e7"}
                %td{:width => "1"}
        / end Comment
        %tr
          %td{:align => "center", :style => "padding:10px 0 30px;"}
            %h4{:style => "font-family:georgia,serif;font-weight:normal;font-size:21px;color:#211922 !important;text-shadow:0 1px 0 #FFFFFF;margin:0;padding:0;"} Happy pinning!
        / begin Badge Rule
        %tr
          %td#badge_rule{:align => "center", :background => "http://passets-ec.pinterest.com/images/mail/badge_rule620.gif", :height => "18", :width => "100%"}
        / end Badge Rule
        / begin Subscription Notification
        %tr
          %td{:align => "center", :style => "padding:30px 0 15px;"}
        / end Subscription Notification
        / begin Copyright and Legal
        %tr
          %td{:align => "center"}
            %p{:style => "font-family:'helvetica neue',helvetica,arial,sans-serif;font-size:10px;color:#999999;text-shadow:0 1px 0 #FFFFFF;line-height:1.35em;margin:0;padding:0;"}
              %span.symbolfix> ©
              2014 Pinterest, Inc.
              %font{:style => "color:#AAA;padding:0 2px;"} |
              All Rights Reserved
              %br/
              %a{:href => "http://www.pinterest.com/about/privacy/", :style => "color:#999;text-decoration:underline;text-shadow:0 1px 0 #FFFFFF;"} Privacy Policy
              %font{:style => "color:#AAA;padding:0 2px;"} |
              %a{:href => "http://www.pinterest.com/about/terms/", :style => "color:#999;text-decoration:underline;text-shadow:0 1px 0 #FFFFFF;"} Terms and Conditions
        / end Copyright and Legal

app/views/pages/privacy.html.haml
%div{:'ng-controller' => "PagesCtrl"}
  .main-content.privacy-content
    .center
      %h2 Privacy Policy
      %p FANTEES PTY LTD, the publisher of this website (hereinafter “the publisher”) understands how important your privacy is. That is why whenever we deal with any personal details, or information about you, we always act in accordance with the Privacy Act 1988 (Cth)
      %p
        %strong Your Personal Information
      %p Personal Information is defined as any information or opinion about you. This can include a variety of general information, such as your address and phone number, to more detailed and sensitive information, such as your annual income or pre-existing medical conditions. The publisher will collect personal information from time to time, but only when a person actively submits the information. As a rule, we do not collect, nor have any use for, information about your religious orientation, sexual orientation, medical conditions, ethnic origin etc.
      %p
        %strong Who Collects Your Personal Information
      %p Your personal information will only be collected by an authorised representative of the publisher. These representatives are generally employees of the publisher, who have been specifically trained to collect and deal appropriately with the sensitive nature of the information we require. Under no circumstances will your personal information ever be disclosed, sold or passed on to a third party, unless specifically and explicitly authorised by you.
      %p
        %strong How Your Information Will Be Collected
      %p The publisher will only collect the information when customers of the publisher enter that information through the website. This information will be collected from you directly when you express an interest in becoming a client / customer of the publisher. Such information will be collected in a variety of ways:
      %ol
        %li Through registering your contact information and any other personal details online, through this Website;
        %li When you complete an electronic, online form through this website at the abovementioned URL;
        %li When you complete a hard copy, printed form obtained either directly from the publisher from a sales representative, or through this website at the abovementioned URL;
        %li When you contact the publisher directly by phone or in person.
      %p
        %strong Storage
      %p The publisher takes great care to store your personal information in such a way as to protect such information from unauthorised access. Your personal information will be stored in a combination of secure computer storage, paper based secure files and other secure recording devices. The publisher makes every effort to ensure your personal information is not lost, misused, stolen, disclosed or abused by anyone.
      %p
        %strong Using Your Personal Information
      %p The publisher will only use the personal information you have provided in the following but not limited to, situations: to advise clients / customers of up-coming exclusive and non-exclusive offers to provide clients / customers with any information that they have requested to assist clients / customers in any way in which they request assistance.
      %p
        %strong Disclosure of Your Personal Information
      %p The publisher will not disclose your personal information in any form, for any reason whatsoever. You personal details and email address will never be sold, traded, given away, disclosed to other users unless requested or allowed by you, or generally disclosed for any reason whatsoever.
      %p
        %strong Keeping Records
      %p The publisher make all reasonable effort to ensure that any personal information that we collect, use and disclose, is correct. However, should any of the personal details and information that we collect, change in any way, it would be appreciated if you could advise the publisher so that our ecords can be updated and continue to be of service to you.
      %p
        %strong Website analytics
      %p To improve your experience on our site, we may use 'cookies'. Cookies are an industry standard and most major web sites use them. A cookie is a small text file that our site may place on your computer as a tool to remember your preferences. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website.
      %p Our website may contain links to other websites. Please be aware that we are not responsible for the privacy practices of such other sites. When you go to other websites from here, we advise you to be aware and read their privacy policy.
      %p Our website uses Google Analytics, a service which transmits website traffic data to Google servers in the United States. Google Analytics does not identify individual users or associate your IP address with any other data held by Google. We use reports provided by Google Analytics to help us understand website traffic and webpage usage.
      %p
        By using this website, you consent to the processing of data about you by Google in the manner described in
        %a{:href => "http://www.google.com/policies/privacy/"} Google's Privacy Policy
        and for the purposes set out above. You can opt out of Google Analytics if you disable or refuse the cookie, disable JavaScript, or
        %a{:href => "https://tools.google.com/dlpage/gaoptout"} use the opt-out service provided by Google.
      %p FanTees.com.au also uses interfaces with social media sites such as Facebook, LinkedIn, Twitter and others. If you choose to "like" or “share” information from this website through these services, you should review the privacy policy of that service. If you are a member of a social media site, the interfaces may allow the social media site to connect your visits to this site with other Personal Information.
      %p
        %strong Our obligations
      %p
        This online service is bound by the provisions of the
        = succeed "," do
          %a{:href => "http://www.google.com/url?q=http%3A%2F%2Fwww.comlaw.gov.au%2FSeries%2FC2004A03712&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNG20gOLd_K8Kyl6uScFicjlSXvMnA"} Privacy Act 1988 (Cth)
        including the
        = succeed "." do
          %a{:href => "http://www.google.com/url?q=http%3A%2F%2Fwww.oaic.gov.au%2Fprivacy%2Fprivacy-act%2Faustralian-privacy-principles&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHk-rMhQixmhczOLfQfhyA8cxcFuw"} Australian Privacy Principles
      %p
        %strong Contact us
      %p
        = link_to "Contact us about your privacy concerns.", "/contact-us"
      %p Alternatively, you can write to us at:
      %p
        Manager, FANTEES Pty Ltd
        %br
          Brendale Business Hub
          %br
            PO BOX 5583
            %br
              Brendale DC, QLD, 4500
              %br Australia

app/views/pages/processing.html.haml
.main-content.process-content
  .center
    .header-infographics
      .container

    .title-infographics
      .container
        .row
          .col-md-12
            %h1
              FanTees made for you
              %span Process

    .content-infographics
      .container
        .row
          .col-md-12.separator

            .spacer2
            .col-md-5.text-center
              = image_tag "day1-img.png"
            .col-md-2
            .col-md-5
              %h2 Day 1
              %p So today we’re preparing everything for print so the printing process is as smooth as possible. We also put our blank tee and hoodie order in with suppliers.
            .clearfix

            .col-md-5
              .spacer2
              %h2 Day 2-5
              %p We finish setting everything up for printing while our supplier delivers our blanks.
            .col-md-2
            .col-md-5.text-center
              = image_tag "day2to7.png"
            .clearfix

            .col-md-5.text-center
              = image_tag "day8to14.png"
            .col-md-2
            .col-md-5
              .spacer2
                %h2 Day 6-7
                %p We start printing (using the Soft Hand method to ensure the print doesn’t fade or leave the chunky print that we all hate!)
            .clearfix

            .col-md-5
              .spacer2
              %h2 Day 8-10
              %p This is the fun bit, we fold and bag each of the orders ready to be shipped out to you!</p>
            .col-md-2
            .col-md-5.text-center
              = image_tag "day15to17.png"
            .clearfix

            .col-md-5.text-center
              = image_tag "day18.png"
            .col-md-2

            .col-md-5
              .spacer2
              %h2 Day 10-12
              %p I love this day, because it’s when we package everything together ready to be picked up by the postman to be express posted to you. Yup, after this your orders will be on their way via express post!!!</p>

            .clearfix
            .col-md-5
              .spacer2
              .spacer
              %h2 Day 12-14
              %p Depending on where you live, you’ll be receiving your order on your doorstep by one of the very lovely Australia Post postmen!</p>
            .col-md-2

            .col-md-5.text-center
              = image_tag "day19to21.png"
              .spacer2
            .clearfix

app/views/pages/user_agreement.html.haml
.main-content.shipping-content
  .center
    %h2 User Agreement
    %p
      %strong By violating this user agreement in any capacity, you are subject to an immediate removal of your campaign(s), possible forfeit of profit(s), and potential suspension or termination of your account.
    %p
      %strong By creating a campaign on the FanTees site:
    %ul.page-list
      %li You agree to accept and abide by FanTees Terms of Service in their entirety;
      %li You have explicit, written permission to us any trademarks or copyrights in your designs from the holder of the intellectual property rights;
      %li You agree to refrain from using any copyrights or trademarks in your page text, headline or URL;
      %li You understand and agree that your contact information will be released to a verified complainant of intellectual property infringement;
      %li You agree not to include any offensive, racist, sexist or overtly sexual material in your design, page text, headline or URL;
      %li You agree not to include any reference to the death of an individual or individuals without express written consent from the individual(s) next of kin;
      %li You will not promote your design through means that are against any of the relevant platforms Terms Of Service, or use any “Automated” tools or software to do so;
      %li You will not in any way, shape or form, conduct your promotion of your design in such a matter to damage or bring disrepute to the FanTees brand;
      %li You agree to defend, indemnify and hold FanTees and its affiliates harmless from and against any and all claims, damages, costs and expenses, including reasonable lawyers' fees, arising from or relating to your use of FanTees site and services, your violation of this agreement, or your violation of any rights of another.
      %li You agree that FanTees is not responsible for any damages whatsoever (consequential, indirect or any special damages) including, but not limited to, lost profits, associated with any action taken by FanTees pursuant to this Agreement or your use of the FanTees service.
      %li That at FanTees sole discretion any breach of the above terms may result in cancellation of campaign, forfeiture of any profits earned and cancellation of your FanTees account.
/ success-page-content

app/views/pages/win.html.haml
%div{:'ng-controller' => "PagesCtrl"}
  #content-wrapper{style: "min-height: {{height}}"}
    .container
      %a.e-widget.generic-loader{ :href => "https://gleam.io/GEnz5/win-a-years-supply-of-tees", :rel => "nofollow" } Win A Year&#39;s Supply Of Tees!
      %script{ :src => "https://js.gleam.io/e.js", :async => "true" }